#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KEYWORDS_FILE = ROOT / "apps" / "oaboutai" / "data" / "keywords.json"


def normalize_alias(value: str) -> str:
    text = str(value or "").strip().lower()
    if not text:
        return ""
    return re.sub(r"\s+", " ", text)


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_alias_pairs() -> list[tuple[str, str]]:
    rows = json.loads(KEYWORDS_FILE.read_text(encoding="utf-8"))
    if not isinstance(rows, list):
        raise SystemExit("keywords.json must be a list")

    alias_to_id: dict[str, str] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        keyword_id = normalize_alias(row.get("id", ""))
        if not keyword_id:
            continue

        candidates: list[str] = [keyword_id]
        label = row.get("label", {})
        if isinstance(label, dict):
            candidates.extend(str(v) for v in label.values())
        aliases = row.get("aliases", [])
        if isinstance(aliases, list):
            candidates.extend(str(v) for v in aliases)

        for candidate in candidates:
            alias = normalize_alias(candidate)
            if not alias:
                continue
            alias_to_id.setdefault(alias, keyword_id)

    return sorted(alias_to_id.items(), key=lambda item: item[0])


def render_sql(alias_pairs: list[tuple[str, str]]) -> str:
    values = ",\n  ".join(f"({sql_quote(alias)}, {sql_quote(keyword_id)})" for alias, keyword_id in alias_pairs)
    return f"""-- Generated by scripts/generate_keyword_normalization_sql.py
-- Purpose:
-- 1) map Chinese/alias keywords to canonical English ids from data/keywords.json
-- 2) lowercase + trim all keyword tokens
-- 3) deduplicate per article while preserving first-seen order

begin;

create temp table keyword_alias_map (
  alias text primary key,
  keyword_id text not null
) on commit drop;

insert into keyword_alias_map(alias, keyword_id)
values
  {values}
;

with expanded as (
  select
    a.slug,
    a.language,
    k.ordinality as ord,
    lower(trim(k.value)) as kw_raw
  from public.articles as a
  cross join lateral jsonb_array_elements_text(coalesce(a.keywords, '[]'::jsonb))
    with ordinality as k(value, ordinality)
),
mapped as (
  select
    e.slug,
    e.language,
    e.ord,
    coalesce(m.keyword_id, regexp_replace(e.kw_raw, '\\s+', ' ', 'g')) as kw_norm
  from expanded as e
  left join keyword_alias_map as m
    on m.alias = regexp_replace(e.kw_raw, '\\s+', ' ', 'g')
),
dedup as (
  select
    slug,
    language,
    kw_norm,
    min(ord) as first_ord
  from mapped
  where kw_norm <> ''
  group by slug, language, kw_norm
),
rebuilt as (
  select
    slug,
    language,
    jsonb_agg(kw_norm order by first_ord) as keywords_new
  from dedup
  group by slug, language
)
update public.articles as a
set keywords = r.keywords_new
from rebuilt as r
where a.slug = r.slug
  and a.language = r.language
  and a.keywords is distinct from r.keywords_new
;

-- Any rows returned below still contain non-canonical tokens and may need manual mapping.
select
  a.slug,
  a.language,
  kw as unresolved_keyword
from public.articles as a
cross join lateral jsonb_array_elements_text(coalesce(a.keywords, '[]'::jsonb)) as t(kw)
where kw !~ '^[a-z0-9-]+$'
order by a.slug, a.language, kw
;

commit;
"""


def main() -> int:
    if not KEYWORDS_FILE.exists():
        raise SystemExit(f"Missing keywords file: {KEYWORDS_FILE}")
    alias_pairs = build_alias_pairs()
    print(render_sql(alias_pairs))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
