-- Generated by scripts/generate_keyword_normalization_sql.py
-- Purpose:
-- 1) map Chinese/alias keywords to canonical English ids from data/keywords.json
-- 2) lowercase + trim all keyword tokens
-- 3) deduplicate per article while preserving first-seen order

begin;

create temp table keyword_alias_map (
  alias text primary key,
  keyword_id text not null
) on commit drop;

insert into keyword_alias_map(alias, keyword_id)
values
  ('adversarial testing', 'red-teaming'),
  ('adversarial-ml', 'red-teaming'),
  ('ai sovereignty', 'sovereign-ai'),
  ('ai-legislation', 'regulation'),
  ('ai主權', 'sovereign-ai'),
  ('assurance', 'audit'),
  ('assurance cases', 'safety-cases'),
  ('audit', 'audit'),
  ('benchmarking', 'model-evaluation'),
  ('compliance', 'regulation'),
  ('compliance law', 'regulation'),
  ('content-moderation', 'risk-management'),
  ('defense-governance', 'governance-framework'),
  ('digital sovereignty', 'sovereign-ai'),
  ('enterprise-adoption', 'governance-framework'),
  ('enterprise-ai', 'governance-framework'),
  ('eval', 'model-evaluation'),
  ('governance framework', 'governance-framework'),
  ('governance-framework', 'governance-framework'),
  ('human-oversight', 'risk-management'),
  ('implementation-governance', 'governance-framework'),
  ('incident disclosure', 'incident-reporting'),
  ('incident reporting', 'incident-reporting'),
  ('incident-reporting', 'incident-reporting'),
  ('law', 'regulation'),
  ('licensing', 'regulation'),
  ('model evaluation', 'model-evaluation'),
  ('model-evaluation', 'model-evaluation'),
  ('national ai sovereignty', 'sovereign-ai'),
  ('policy framework', 'governance-framework'),
  ('public consultation', 'public-consultation'),
  ('public-consultation', 'public-consultation'),
  ('public-sector-ai', 'governance-framework'),
  ('red teaming', 'red-teaming'),
  ('red-teaming', 'red-teaming'),
  ('regional-innovation', 'governance-framework'),
  ('regulation', 'regulation'),
  ('risk control', 'risk-management'),
  ('risk governance', 'risk-management'),
  ('risk management', 'risk-management'),
  ('risk-management', 'risk-management'),
  ('safety cases', 'safety-cases'),
  ('safety-cases', 'safety-cases'),
  ('security-architecture', 'safety-cases'),
  ('sovereign ai', 'sovereign-ai'),
  ('sovereign-ai', 'sovereign-ai'),
  ('stakeholder consultation', 'public-consultation'),
  ('standardization', 'standards'),
  ('standards', 'standards'),
  ('threat-modeling', 'risk-management'),
  ('usage-analytics', 'safety-cases'),
  ('主權ai', 'sovereign-ai'),
  ('事故通報', 'incident-reporting'),
  ('公眾諮詢', 'public-consultation'),
  ('安全案例', 'safety-cases'),
  ('標準', 'standards'),
  ('模型評估', 'model-evaluation'),
  ('治理框架', 'governance-framework'),
  ('法規', 'regulation'),
  ('稽核', 'audit'),
  ('紅隊測試', 'red-teaming'),
  ('風險管理', 'risk-management')
;

with expanded as (
  select
    a.slug,
    a.language,
    k.ordinality as ord,
    lower(trim(k.value)) as kw_raw
  from public.articles as a
  cross join lateral jsonb_array_elements_text(coalesce(a.keywords, '[]'::jsonb))
    with ordinality as k(value, ordinality)
),
mapped as (
  select
    e.slug,
    e.language,
    e.ord,
    coalesce(m.keyword_id, regexp_replace(e.kw_raw, '\s+', ' ', 'g')) as kw_norm
  from expanded as e
  left join keyword_alias_map as m
    on m.alias = regexp_replace(e.kw_raw, '\s+', ' ', 'g')
),
dedup as (
  select
    slug,
    language,
    kw_norm,
    min(ord) as first_ord
  from mapped
  where kw_norm <> ''
  group by slug, language, kw_norm
),
rebuilt as (
  select
    slug,
    language,
    jsonb_agg(kw_norm order by first_ord) as keywords_new
  from dedup
  group by slug, language
)
update public.articles as a
set keywords = r.keywords_new
from rebuilt as r
where a.slug = r.slug
  and a.language = r.language
  and a.keywords is distinct from r.keywords_new
;

-- Any rows returned below still contain non-canonical tokens and may need manual mapping.
select
  a.slug,
  a.language,
  kw as unresolved_keyword
from public.articles as a
cross join lateral jsonb_array_elements_text(coalesce(a.keywords, '[]'::jsonb)) as t(kw)
where kw !~ '^[a-z0-9-]+$'
order by a.slug, a.language, kw
;

commit;

